name: Changelog

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'docs/**'
      - '**.md'
      - '.github/workflows/**'

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install GitPython
      run: |
        python -m pip install --upgrade pip
        pip install gitpython
    
    - name: Generate changelog
      id: generate_changelog
      run: |
        python .github/scripts/generate_changelog.py > CHANGELOG.md
    
    - name: Check if CHANGELOG.md changed
      id: check_changes
      run: |
        if git diff --quiet CHANGELOG.md; then
          echo "No changes to CHANGELOG.md"
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "CHANGELOG.md was updated"
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG.md [skip ci]"
        git push
