name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/release.yml'
      - '.github/workflows/changelog.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/release.yml'
      - '.github/workflows/changelog.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: orbit
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          orbit/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('orbit/**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      working-directory: ${{ github.workspace }}/orbit
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
    
    - name: Build
      working-directory: ${{ github.workspace }}/orbit
      run: cargo build --verbose
    
    - name: Run tests
      working-directory: ${{ github.workspace }}/orbit
      run: cargo test --verbose
    
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: orbit
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Check formatting
      working-directory: ${{ github.workspace }}/orbit
      run: cargo fmt --all -- --check
    
    - name: Run clippy
      working-directory: ${{ github.workspace }}/orbit
      run: cargo clippy -- -D warnings
